create table application_metadata (
    id bigint generated by default as identity primary key,
    metadata_key varchar(120) not null unique,
    metadata_value varchar(500) not null,
    created_at timestamp with time zone not null default current_timestamp
);

insert into application_metadata (metadata_key, metadata_value)
values ('schema_version_note', 'FlowPilot AI backend foundation initialized');
