create table users (
    id bigint generated by default as identity primary key,
    email varchar(320) not null unique,
    display_name varchar(120) not null,
    password_hash varchar(255) not null,
    role varchar(40) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint users_role_check check (role in ('ADMIN', 'MANAGER', 'SUPPORT_AGENT'))
);

create index idx_users_email on users (email);
