create table cases (
    id bigint generated by default as identity primary key,
    title varchar(160) not null,
    description text not null,
    customer_name varchar(120) not null,
    customer_email varchar(320),
    customer_tier varchar(30) not null,
    order_reference varchar(80),
    order_value numeric(12, 2),
    priority varchar(20) not null,
    status varchar(40) not null,
    created_by bigint not null references users (id),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint cases_customer_tier_check check (customer_tier in ('STANDARD', 'PREMIUM')),
    constraint cases_priority_check check (priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    constraint cases_status_check check (
        status in ('OPEN', 'IN_PROGRESS', 'PENDING_MANAGER_REVIEW', 'RESOLVED', 'CLOSED')
    ),
    constraint cases_order_value_check check (order_value is null or order_value >= 0)
);

create index idx_cases_created_by on cases (created_by);
create index idx_cases_status on cases (status);
create index idx_cases_priority on cases (priority);
create index idx_cases_created_at on cases (created_at desc);
