create table knowledge_documents (
    id bigint generated by default as identity primary key,
    file_name varchar(255) not null,
    content_type varchar(150) not null,
    size_bytes bigint not null,
    status varchar(30) not null,
    chunk_count integer not null default 0,
    error_message varchar(500),
    uploaded_by bigint not null references users (id),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint knowledge_documents_size_check check (size_bytes > 0),
    constraint knowledge_documents_status_check check (status in ('PROCESSING', 'READY', 'FAILED')),
    constraint knowledge_documents_chunk_count_check check (chunk_count >= 0)
);

create index idx_knowledge_documents_status on knowledge_documents (status);
create index idx_knowledge_documents_uploaded_by on knowledge_documents (uploaded_by);
create index idx_knowledge_documents_created_at on knowledge_documents (created_at desc);
